--Timothy Ian Anderson
--CIS 2454
--Integrated Project

CREATE TABLE `customer` (
  `CUST_ID` varchar(5) NOT NULL,
  `CUST_NAME` varchar(64) NOT NULL,
  `CUST_ADDRESS` varchar(96) NOT NULL,
  `CUST_PHONENUMBER` varchar(10) NOT NULL,
  `CUST_DEBITNUMBER` varchar(15) NOT NULL,
  `CUST_DEBITBALANCE` decimal(7,2) NOT NULL,
  PRIMARY KEY (`CUST_ID`),
  UNIQUE KEY `CST_DEBITNUM` (`CUST_DEBITNUMBER`)
) ENGINE=MEMORY DEFAULT CHARSET=utf8	

CREATE TABLE `financialhistory` (
  `FIN_ID` varchar(5) NOT NULL,
  `FIN_CUSTID` varchar(5) NOT NULL,
  `FIN_TRANSACTONAMNT` decimal(7,2) NOT NULL,
  `FIN_DATE` date NOT NULL,
  PRIMARY KEY (`FIN_ID`)
) ENGINE=MEMORY DEFAULT CHARSET=utf8	

CREATE TABLE `reservations` (
  `RES_ID` varchar(5) NOT NULL,
  `RES_ITEMID` varchar(5) NOT NULL,
  `RES_STATUS` varchar(16) NOT NULL,
  `RES_TRAVELERS` int(11) NOT NULL,
  `RES_STARTDATE` date NOT NULL,
  `RES_ENDDATE` date NOT NULL,
  `RES_CUSTID` varchar(5) NOT NULL,
  PRIMARY KEY (`RES_ID`)
) ENGINE=MEMORY DEFAULT CHARSET=utf8	

CREATE TABLE `rewards` (
  `REWARD_ID` varchar(5) NOT NULL,
  `REWARD_CUSTID` varchar(5) NOT NULL,
  `REWARD_BALANCE` float(7,2) NOT NULL,
  `REWARD_DATE` date NOT NULL,
  PRIMARY KEY (`REWARD_ID`)
) ENGINE=MEMORY DEFAULT CHARSET=utf8	

CREATE TABLE `travelitems` (
  `TRAVITEM_ID` varchar(5) NOT NULL,
  `TRAVITEM_TYPE` varchar(16) NOT NULL,
  `TRAVITEM_DESC` varchar(32) NOT NULL,
  `TRAVITEM_COST` decimal(7,2) NOT NULL,
  `TRAVITEM_AVAIL` int(11) NOT NULL,
  `TRAVITEM_FEAT1` varchar(64) NOT NULL,
  `TRAVITEM_FEAT2` varchar(64) NOT NULL,
  `TRAVITEM_FEAT3` varchar(64) NOT NULL,
  PRIMARY KEY (`TRAVITEM_ID`)
) ENGINE=MEMORY DEFAULT CHARSET=utf8	

CREATE TABLE `travelitems` (
  `TRAVITEM_ID` varchar(5) NOT NULL,
  `TRAVITEM_TYPE` varchar(16) NOT NULL,
  `TRAVITEM_DESC` varchar(32) NOT NULL,
  `TRAVITEM_COST` decimal(7,2) NOT NULL,
  `TRAVITEM_AVAIL` int(11) NOT NULL,
  `TRAVITEM_FEAT1` varchar(64) NOT NULL,
  `TRAVITEM_FEAT2` varchar(64) NOT NULL,
  `TRAVITEM_FEAT3` varchar(64) NOT NULL,
  PRIMARY KEY (`TRAVITEM_ID`)
) ENGINE=MEMORY DEFAULT CHARSET=utf8	
